sistemaCotizacion/config/routes.rb
Rails.application.routes.draw do
  get 'index/index'

  root 'index#index'

  post '/updateProducts' => 'quotations#updateProducts'

  post '/updateClient' => 'quotations#updateClient'

  post '/findProductsById' => 'products#findProductsById'

  get '/clientData' => 'quotations#show'

  post '/createFromProducts' => 'quotations#createFromProducts'

  resources :quotations, shallow: true do
    resources :clients
    resources :advisers
    resources :services
    resources :activities
    resources :articles
    resources :products
  end

  resources :services, shallow: true do
    resources :quotations
    resources :activities
  end

  resources :activities, shallow: true do
    resources :activity_types
    resources :construction_types
    resources :services
    resources :quotations
  end

  resources :products, shallow: true do
   resources :material_type
   resources :construction_type
   resources :articles
   resources :quotations
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sistemaCotizacion/app/models/quotation.rb
=begin
 * Modelo de la tabla Quotation de la base de datos
 * @author rails
 * @version 14-10-2017
=end
class Quotation < ApplicationRecord
  belongs_to :client
  belongs_to :adviser
  has_many :services
  has_many :activities, through: :services
  has_many :articles
  has_many :products, through: :articles

  validates :name, format: {with: /\A[a-zA-Z ]+\p{Latin}+\z/, message: "El nombre solo puede contener letras"}, length: { maximum: 50 }, presence: true
  validates :floor_length, numericality: true, presence: true
  validates :floor_width, numericality: true, presence: true
  validates :wall_height, numericality: true, presence: true
  validates :wall_width, numericality: true, presence: true
  validates :budget, numericality: { only_integer: true }, presence: true
  validates :project_status, format: {with: /\A[a-zA-Z ]+\p{Latin}+\z/, message: "El estado de la obra solo puede contener letras"}, length: { maximum: 11 }, presence: true

=begin
 * calcula el total de metros cuadrados que requiere el proyecto
 * @return metros cuadrados totales
=end
  def totalMeters
    (self.floor_width*self.floor_length)
  end

=begin
 * obtiene el presupuesto de la cotización
 * @return presupuesto de la cotización
=end
  def getBudget
    ActionController::Base.helpers.number_to_currency(self.budget, precision: 0, delimiter: ".")
  end

=begin
 * calcula el valor total de todos los servicios de instalación del proyecto
 * @return valor total de todos los servicios
=end
  def totalValueServices
    total = self.activities.map {|activity| activity['value_meter']}.reduce(:+)
    valueService = total*self.totalMeters
    return valueService
  end

=begin
 * calcula el valor total de todos los productos del proyecto
 * @param quantity cantidad del producto necesario para la obra
 * @return valor total de todos los productos
=end
  def totalValueProducts(quantity)
    total = self.products.map {|product| product.getValue(quantity)}.reduce(:+)
    return total
  end

=begin
 * calcula el valor total de la cotización, de todos los servicios y productos
 * @param quantity cantidad del producto necesario para la obra
 * @return valor total de la cotización
=end
  def totalValueQuotation(quantity)
    totalQuotation = totalValueServices + totalValueProducts(quantity)
    return totalQuotation
  end

=begin
 * le da el formato de moneda al valor de todos los servicios
 * @return valor total de los servicios con el formato de moneda requerido
=end
  def getValueAllServices
    ActionController::Base.helpers.number_to_currency(totalValueServices, precision: 0, delimiter: ".")
  end

=begin
 * le da el formato de moneda al valor de todos los productos
 * @param quantity cantidad del producto necesario para la obra
 * @return valor total de los productos con el formato de moneda requerido
=end
  def getValueAllProducts(quantity)
    ActionController::Base.helpers.number_to_currency(totalValueProducts(quantity), precision: 0, delimiter: ".")
  end

=begin
 * le da el formato de moneda al valor de la cotización, los productos más los servicios
 * @param quantity cantidad del producto necesario para la obra
 * @return valor total de la cotización con el formato de moneda requerido
=end
  def getValueAllQuotation(quantity)
    totalAll = totalValueServices + totalValueProducts(quantity)
    all = ActionController::Base.helpers.number_to_currency(totalAll, precision: 0, delimiter: ".")
    return all
  end

end

sistemaCotizacion/app/controllers/quotations_controller.rb
=begin
 * Controlador para el modelo Quotation
 * @author rails
 * @version 14-10-2017
=end

class QuotationsController < ApplicationController

=begin
 * Obtiene la cotización con el id que llega por parámetro y redirecciona para su visualización
 * @return  la cotización que va a ser mostrada al cliente
=end
  def index
    respond_to do |format|
      format.html { redirect_to quotations_path }
      format.js   {
        @quotation = Quotation.find(params[:id])
      }
    end
  end

  def show

  end

  def new
    @quotation = Quotation.new
  end

=begin
 * Crea una nueva cotización con los parámetros dados por el usuario
 * @return  la cotización creada con los parámetros del cliente, los productos disponibles para su proyecto de acuerdo a su presupuesto
 * y los servicios de instalación que requiere según su proyecto
=end
  def create
    respond_to do |format|
      format.html { redirect_to quotations_path }
      format.js   {
                    @quotation = Quotation.new(quotation_params)
                    @quotation.save!
                    @line = findLine
                    if params.dig(:quotation, :service).to_i == 1
                      if params.dig(:quotation, :name).eql?("Baño")
                        findActivities(@quotation, 1, params.dig(:quotation, :project_status))
                        findProductsBudget(@quotation,params.dig(:quotation, :budget).to_i, 1)
                      elsif params.dig(:quotation, :name).eql?("Cocina")
                        findActivities(@quotation, 2, params.dig(:quotation, :project_status))
                        findProductsBudget(@quotation,params.dig(:quotation, :budget).to_i, 2)
                      end
                    else
                      if params.dig(:quotation, :name).eql?("Baño")
                        findProductsBudget(@quotation,params.dig(:quotation, :budget).to_i, 1)
                      elsif params.dig(:quotation, :name).eql?("Cocina")
                        findProductsBudget(@quotation,params.dig(:quotation, :budget).to_i, 1)
                      end
                    end
                  }
                end
  end

=begin
 * Asigna los productos seleccionados por el cliente a su cotización
 * @return  la cotización completa con los productos y servicios que desea el cliente
=end
  def updateProducts
    respond_to do |format|
      format.html { redirect_to quotations_path }
      format.js   {
        Article.where("quotation_id = :quotation", quotation: params.dig(:selected, :quotation)).destroy_all
        @quotation = Quotation.find(params.dig(:selected, :quotation))
        findProductsSelected(@quotation, params.keys)
      }
    end
  end

=begin
 * Obtiene las servicios de instalación dependiendo del estado y el tipo de la obra
 * @param construction_type que construcción se quiere realizar o modificar
 * @param quotation cotización a la cual se le van a añadir los servicios
 * @param project_status el estado de la obra permite seleccionar los servicios pertientes
 * @return  la cotización con los servicios que desea el cliente
=end
  def findActivities(quotation, construction_type, project_status)
    if project_status.eql?("Obra Negra")
      @activities = Activity.where("construction_type_id = :construction_type AND activity_type_id <> :activity_type",{construction_type: construction_type, activity_type: 2}).order('id desc')
    elsif project_status.eql?("Obra Blanca")
      @activities = Activity.where(construction_type_id: construction_type).order('id desc')
    end
    @activities.each do |activity|
      @service = quotation.services.create(quotation_id: quotation.id, activity_id: activity.id)
    end
    return @service
  end

=begin
 * Encuentra los productos que se ajustan al presupuesto dado por el cliente
 * @param quotation cotización a la cual se le van a añadir los productos
 * @param budget monto dado por el cliente
 * @param construction_type que construcción se quiere realizar o modificar
 * @return  la cotización con los productos que desea el cliente
=end
  def findProductsBudget(quotation, budget, construction_type)
    if budget >= @line.min_value and budget < @line.max_value
    @products = Product.where("product_line_id = :line_id AND construction_type_id = :construction_type", construction_type: construction_type,line_id: @line.id).order('id desc')
      @products.each do |product|
        @article = quotation.articles.create(quotation_id: quotation.id, product_id: product.id, quantity: 1)
      end
    end
    return @article
  end

=begin
 * Obtiene a que línea de productos se ajusta el presupuesto dado por el usuario
 * @return la línea a la que el cliente puede acceder con base a su presupuesto
=end
  def findLine
    lines = ProductLine.all
    lines.each do |line|
      if params.dig(:quotation, :budget).to_i >= line.min_value and params.dig(:quotation, :budget).to_i < line.max_value
        return line
      end
    end
  end

=begin
 * Actualiza los datos del cliente en la cotización
 * @return la cotización con la información del cliente actualizada
=end
  def updateClient
    respond_to do |format|
      format.html { redirect_to quotations_path }
      format.js   {
        @quotation = Quotation.find(params.dig(:client, :quotation))
        if @quotation.client_id == 1
          @client = @quotation.create_client(first_name: params.dig(:client, :first_name), middle_name: params.dig(:client, :middle_name), first_surname: params.dig(:client, :first_surname), second_surname: params.dig(:client, :second_surname), email: params.dig(:client, :email), phone: params.dig(:client, :phone))
          @client.save!
          @quotation.update(client_id: @client.id)
        end
      }
    end
  end

=begin
 * Crea la cotización con los productos seleccionados por el cliente
 * y los datos que proporciona
 * @return la cotización generada
=end
  def createFromProducts
    respond_to do |format|
      format.html { redirect_to quotations_path }
      format.js   {
        @quotation = createQuotation(params)
        @quotation.save!
        findProductsSelected(@quotation, params.keys)
        if params.dig(:selected, :service).to_i == 1
          if params.dig(:selected, :name).eql?("Baño")
            findActivities(@quotation, 1, params.dig(:selected, :project_status))
          elsif params.dig(:selected, :name).eql?("Cocina")
            findActivities(@quotation, 2, params.dig(:selected, :project_status))
          end
        end
      }
    end
  end

=begin
 * Obtiene los productos seleccionados por el cliente y los añade a la cotización
 * @param quotation cotización a la cual se le van a añadir los productos
 * @param budget monto dado por el cliente
 * @return la contización con los productos elegidos por el usuario
=end
  def findProductsSelected(quotation, keys)
    keys.each do|key|
      if key.include?("product")
        value = params.values_at(key)
        @newProduct = Product.find(value)
        @newProduct.each do |pro|
          @article = @quotation.articles.create(quotation_id: @quotation.id, product_id: pro.id, quantity: 1)
        end
      end
    end
    return @article
  end

=begin
 * Crea el objeto contización con unos parámetros definidos
 * @param nombre, presupesto, dimensiones, estado de la obra
 * @return la cotización creada
=end
  def createQuotation(params)
    @quotation = Quotation.new
    @quotation.name = params.dig(:selected, :name)
    @quotation.budget = params.dig(:selected, :budget)
    @quotation.floor_length = params.dig(:selected, :floor_length)
    @quotation.floor_width = params.dig(:selected, :floor_width)
    @quotation.wall_height = params.dig(:selected, :wall_height)
    @quotation.wall_width = params.dig(:selected, :wall_width)
    @quotation.project_status = params.dig(:selected, :project_status)
    return @quotation
  end

=begin
 * Permite verificar si los datos necesarios para la creación de una cotización fueron suministrados
 * @param params todos los parámetros ingresados por el cliente
 * @return la cotización con la información básica
=end
  private
    def quotation_params
      params.require(:quotation).permit(:name, :floor_length, :floor_width, :wall_height, :wall_width, :budget, :project_status)
    end

end

sistemaCotizacion/app/helpers/quotations_helper.rb
module QuotationsHelper
end

sistemaCotizacion/app/views/quotations/_clientData.html.erb
<div class="card col-md-12">
  <div class="card-block">
    <%= form_for :client, url: '/updateClient', remote: true, id:"formUsuario", class: "form-horizontal form-inline my-2 my-lg-0" do |form| %>
    <div style="visibility: hidden"><%= form.text_field :quotation, value: @quotation.id%></div>
    <div class="row">
      <div class="col-md-1"></div>
      <%= form.label :primerNombre, 'Primer Nombre:', class: "col-md-4 text-primary text-center", id:"labelPrimerNombre" %>
      <%= form.text_field :first_name , class: "form-control col-md-5 col-md-5", placeholder: "Ingrese su nombre", id:"first_name"%>
    </div>
    <div class="row">
      <div class="col-md-1"></div>
      <%= form.label :segundoNombre, 'Segundo Nombre:', class: "col-md-4 text-primary text-center", id:"labelSegundoNombre" %>
      <%= form.text_field :middle_name , class: "form-control col-md-5", placeholder: "Sí tiene un segundo nombre, ingréselo", id:"middle_name"%>
    </div>
    <div class="row">
      <div class="col-md-1"></div>
      <%= form.label :primerApellido, 'Primer Apellido:', class: "col-md-4 text-primary text-center", id:"labelPrimerApellido" %>
      <%= form.text_field :first_surname , class: "form-control col-md-5", placeholder: "Ingrese su primer apellido", id:"first_surname"%>
    </div>
    <div class="row">
      <div class="col-md-1"></div>
      <%= form.label :segundoApellido, 'Segundo Apellido:', class: "col-md-4 text-primary text-center", id:"labelSegundoApellido" %>
      <%= form.text_field :second_surname , class: "form-control col-md-5", placeholder: "Ingrese su segundo apellido", id:"Second_surname"%>
    </div>
    <div class="row">
      <div class="col-md-1"></div>
      <%= form.label :correo, 'Correo:', class: "col-md-4 text-primary text-center", id:"labelCorreo" %>
      <%= form.text_field :email , class: "form-control col-md-5", placeholder: "Ingrese su correo electrónico", id:"email"%>
    </div>
    <div class="row">
      <div class="col-md-1"></div>
      <%= form.label :telefono, 'Teléfono:', class: "col-md-4 text-primary text-center", id:"labelTelefono" %>
      <%= form.text_field :phone , class: "form-control col-md-5", placeholder: "Ingrese su teléfono", id:"phone"%>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-6"><%= form.submit 'Guardar Datos De Usuario', class: "btn btn-primary text-center"%></div>
    </div>
    <% end %>
  </div>
</div>

sistemaCotizacion/app/views/quotations/_create.html.erb
<table class="table table-hover table-responsive" id="tablaCotizacion">
  <thead>
    <tr>
      <th class="border-0" colspan="4"><h1 class="text-center text-primary">Cotizaci&oacute;n</h1></th>
    </tr>
    <% if @quotation.client_id != 1 %>
    <tr class="text-primary">
      <th colspan="2">Nombre</th>
      <th>Correo Electr&oacute;nico</th>
      <th>Tel&eacute;fono</th>
    </tr>
    <tr class="table-info text-primary">
      <td colspan="2"><%= @quotation.client.first_name + " " + @quotation.client.first_surname%></td>
      <td><%= @quotation.client.email%></td>
      <td><%= @quotation.client.phone%></td>
    </tr>
    <% end %>
    <tr class="text-primary">
      <th>Tipo Proyecto</th>
      <th>Presupuesto</th>
      <th>Largo</th>
      <th>Ancho</th>
    </tr>
  </thead>
  <tbody class="text-primary">
    <tr class="table-info">
      <td><%= @quotation.name %></td>
      <td><%= @quotation.getBudget %></td>
      <td><%= @quotation.floor_length %></td>
      <td><%= @quotation.floor_width %></td>
    </tr>
  </tbody>
</table>

<h2 class="text-center text-primary">Productos</h2>

<table class="table table-hover table-responsive" id="tablaProductos">
  <thead>
    <tr class="text-primary">
      <th>Id</th>
      <th>Nombre</th>
      <th>Valor</th>
      <th>L&iacute;nea</th>
    </tr>
  </thead>
  <tbody class="text-primary">
<% @quotation.products.each do |product| %>
<tr>
  <td><%= product.id %></td>

  <td>
    <%= product.name %>
  </td>

  <td>
    <%= product.showValue(@quotation.totalMeters) %>
  </td>

  <td>
    <%= product.product_line.name %>
  </td>
</tr>
<% end %>
</tbody>
</table>

<div class="col-md-12">
<h2 class="text-center text-primary">Servicios de instalaci&oacute;n</h2>
</div>
<div class="col-md-12 text-center">
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseServicios" aria-expanded="false" aria-controls="collapseServicios">
          Ver detalles de los servicios de instalaci&oacute;n
        </a>
      </h5>
    </div>
    <div id="collapseServicios" class="collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="card-block">
        <table class="table table-hover table-responsive" id="tablaServicios">
        <thead>
          <tr class="text-primary">
            <th>Nombre</th>
            <th>Tipo de servicio</th>
            <th>Costo</th>
          </tr>
        </thead>
        <tbody class="text-primary">
          <% @quotation.activities.each do |activity| %>
          <tr>
            <td>
              <%= activity.name %>
            </td>
            <td>
              <%= activity.activity_type.name %>
            </td>
            <td>
              <%= activity.totalValue(@quotation.totalMeters)%>
            </td>
            <td>
              <%= link_to "Más Información", activity_path(id: activity.id), remote: true, class: "btn btn-primary btn-block", 'data-toggle': "modal", 'data-target': "#modalDetalles"%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</div>
</div>

<div class="col-md-12">
<table class="table table-hover table-responsive" id="tablaTotales">
  <thead class="text-primary">
    <tr>
      <th colspan="4"><h2 class="text-center">cotizaci&oacute;n sugerida</h2></th>
    </tr>
    <tr class="text-primary">
      <th>Elemento</th>
      <th>Valor</th>
    </tr>
  </thead>
  <tbody>
    <tr class="text-primary">
    <td colspan="3"><h5 class="text-center">Valor total de los productos</h5></td>
    <td>
      <%= @quotation.getValueAllProducts(@quotation.totalMeters)%>
    </td>
  </tr>
    <tr class="text-primary">
    <td colspan="3"><h5 class="text-center">Valor total de los servicios</h5></td>
    <td>
      <%= @quotation.getValueAllServices%>
    </td>
  </tr>

  <% if @quotation.budget >= @quotation.totalValueQuotation(@quotation.totalMeters).to_i %>
    <tr class="table-info text-primary">
      <td colspan="3"><h2 class="text-center">Valor total cotizaci&oacute;n sugerida</h2></td>
      <td>
      <%= @quotation.getValueAllQuotation(@quotation.totalMeters)%>
      </td>
    </tr>
  <% elsif @quotation.budget <= @quotation.totalValueQuotation(@quotation.totalMeters).to_i%>
  <tr class="table-danger text-primary">
      <td colspan="3"><h2 class="text-center">Valor total cotizaci&oacute;n sugerida</h2></td>
      <td>
      <%= @quotation.getValueAllQuotation(@quotation.totalMeters)%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<div class="col-md-12 text-center">
  <div class="row justify-content-center"> <%= link_to "Datos Cliente", quotations_path(id: @quotation.id), remote: true, class: "btn btn-primary btn-lg btn-block container-fluid", 'data-toggle': "modal", 'data-target': "#modalDatosUsuario"%></div>
</div>

sistemaCotizacion/app/views/quotations/_testProducts.html.erb
<% if @quotation.products.length >= 3 %>
<div class="col-md-4">
  <div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header text-primary text-center border-primary">Opci&oacute;n 1</div>
    <%= form_for :selected, url: '/updateProducts', remote: true, id:"formProductos", class: "form-horizontal form-inline my-2 my-lg-0" do |form| %>
    <%= form.fields_for :data do |data|%>
    <div class="card-body text-primary">
      <div style="visibility: hidden"><%= form.text_field :quotation, value: @quotation.id%></div>
    <div class="row">
      <% @quotation.products[0..3].each do |product| %>
      <div style="visibility: hidden"><%= data.text_field :product, 'name'=>["product"+product.id.to_s], value: product.id%></div>
      <div class="col-md-6">
        <%= image_tag(product.image, class: 'rounded img-fluid', alt: 'proyecto base', 'data-toggle':"popover", title: product.name, 'data-content': product.description) %>
      </div>
      <div class="col-md-6">
        <p class="font-weight-bold"><%= product.name %></p>
      </div>
      <% end %>
    </div>
    <% end %>
    <br>
    <div class="row">
      <%= form.submit 'Seleccionar Sugerencia', class: "btn btn-primary btn-block container-fluid"%>
    </div>
  </div>
  <% end %>
  </div>
</div>
<% end %>



<% if @quotation.products.length >= 7 %>
<div class="col-md-4">
  <div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header text-primary text-center border-primary">Opci&oacute;n 2</div>
    <%= form_for :selected, url: '/updateProducts', remote: true, id:"formProductos", class: "form-horizontal form-inline my-2 my-lg-0" do |form| %>
    <%= form.fields_for :data do |data|%>
    <div class="card-body text-primary">
      <div style="visibility: hidden"><%= form.text_field :quotation, value: @quotation.id%></div>
    <div class="row">
      <% @quotation.products[4..7].each do |product| %>
      <div style="visibility: hidden"><%= data.text_field :product, 'name'=>["product"+product.id.to_s], value: product.id%></div>
      <div class="col-md-6">
        <%= image_tag(product.image, class: 'rounded img-fluid', alt: 'proyecto base', 'data-toggle':"popover", title: product.name, 'data-content': product.description) %>
      </div>
      <div class="col-md-6">
        <p class="font-weight-bold"><%= product.name %></p>
      </div>
      <% end %>
    </div>
    <% end %>
    <br>
    <div class="row">
      <%= form.submit 'Seleccionar Sugerencia', class: "btn btn-primary btn-block container-fluid"%>
    </div>
  </div>
  <% end %>
  </div>
</div>
<% end %>

<% if @quotation.products.length >= 11 %>
<div class="col-md-4">
  <div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header text-primary text-center border-primary">Opci&oacute;n 3</div>
    <%= form_for :selected, url: '/updateProducts', remote: true, id:"formProductos", class: "form-horizontal form-inline my-2 my-lg-0" do |form| %>
    <%= form.fields_for :data do |data|%>
    <div class="card-body text-primary">
      <div style="visibility: hidden"><%= form.text_field :quotation, value: @quotation.id%></div>
    <div class="row">
      <% @quotation.products[8..11].each do |product| %>
      <div style="visibility: hidden"><%= data.text_field :product, 'name'=>["product"+product.id.to_s], value: product.id%></div>
      <div class="col-md-6">
        <%= image_tag(product.image, class: 'rounded img-fluid', alt: 'proyecto base', 'data-toggle':"popover", title: product.name, 'data-content': product.description) %>
      </div>
      <div class="col-md-6">
        <p class="font-weight-bold"><%= product.name %></p>
      </div>
      <% end %>
    </div>
    <% end %>
    <br>
    <div class="row">
      <%= form.submit 'Seleccionar Sugerencia', class: "btn btn-primary btn-block container-fluid"%>
    </div>
  </div>
  <% end %>
  </div>
</div>
<% end %>

sistemaCotizacion/app/views/quotations/create.js.erb
$("#budget").val("");
$("#width").val("");
$("#length").val("");
$("#widthPared").val("");
$("#lengthPared").val("");
$("#widthTecho").val("");
$("#lengthTecho").val("");
$("input:checkbox").prop("checked", false);
$("input:radio").prop("checked", false);
$("#rowLengthTecho").show();
$("#rowWidthTecho").show();
$("#containerSugerencias").empty();
$("#containerSugerencias").html("<%= j render(partial: 'testProducts') %>");

sistemaCotizacion/app/views/quotations/createFromProducts.js.erb
  $("#modalProductos").modal('hide');
  $("#containerViewProducts").empty();
  $("#containerViewProducts").html("<%= j render(partial: 'quotations/create') %>");

sistemaCotizacion/app/views/quotations/index.js.erb
$('#modalDatosUsuario').modal('show')
$("#containerDatosUsuario").empty();
$("#containerDatosUsuario").html("<%= j render(partial: 'clientData') %>");

sistemaCotizacion/app/views/quotations/new.html.erb
<%= form_with scope: :quotation, url: quotations_path, class: "form-horizontal" do |form| %>
<div class="control-group col-xs-12">
  <%= form.label :tipo, class: "control-label" %>
<%= form.select(:name,
options_for_select([['Baño', 'Baño'], ['Cocina','Cocina']])) %>
</div>
<div class="control-group col-xs-12">
    <%= form.label :ancho, class: "control-label" %>
    <div class="controls">
      <%= form.text_field :width %>
    </div>
</div>
<div class="control-group col-xs-12">
    <%= form.label :largo, class: "control-label" %>
    <div class="controls">
      <%= form.text_field :length %>
    </div>
</div>
<div class="control-group col-xs-12">
    <%= form.label :cedula, class: "control-label" %>
    <div class="controls">
      <%= form.text_field :client_id %>
    </div>
    <div style="visibility:hidden" class="controls">
      <%= form.text_field :adviser_id, value: 1%>
    </div>
</div>
<br>
<div class="control-group col-xs-12">
      <%= form.submit :generar, class: "btn btn-primary"%>
</div>
<% end %>

sistemaCotizacion/app/views/quotations/updateClient.js.erb
$("#modalDatosUsuario").modal('hide');
$("#contenidoCotizacion").empty();
$("#contenidoCotizacion").html("<%= j render(partial: 'create') %>");

sistemaCotizacion/app/views/quotations/updateProducts.js.erb
$("#modalSugerencias").modal('hide');
$("#contenidoCotizacion").empty();
$("#contenidoCotizacion").html("<%= j render(partial: 'create') %>");