sistemaCotizacion/config/routes.rb
Rails.application.routes.draw do
  get 'index/index'

  root 'index#index'

  post '/updateProducts' => 'quotations#updateProducts'

  post '/updateClient' => 'quotations#updateClient'

  post '/findProductsById' => 'products#findProductsById'

  get '/clientData' => 'quotations#show'

  post '/createFromProducts' => 'quotations#createFromProducts'

  resources :quotations, shallow: true do
    resources :clients
    resources :advisers
    resources :services
    resources :activities
    resources :articles
    resources :products
  end

  resources :services, shallow: true do
    resources :quotations
    resources :activities
  end

  resources :activities, shallow: true do
    resources :activity_types
    resources :construction_types
    resources :services
    resources :quotations
  end

  resources :products, shallow: true do
   resources :material_type
   resources :construction_type
   resources :articles
   resources :quotations
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sistemaCotizacion/app/views/index/index.html.erb
        <div class="modal fade bd-example-modal-lg" id="modalSugerencias" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <span><%= image_tag('LogoCorona.png', class: 'rounded img-fluid', alt: 'Logo Corona') %></span>
                <h5 class="modal-title text-primary text-center" id="modalTitleSugerencias">Sugerencias de cotizaci&oacute;n</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <br>
              <div class="modal-body">
                <div class="row" id="containerSugerencias">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade bd-example-modal-lg" id="modalDetalles" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <span><%= image_tag('LogoCorona.png', class: 'rounded img-fluid', alt: 'Logo Corona') %></span>
                <h5 class="modal-title text-primary text-center" id="modalTitleDetalles">Detalles Servicio</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <br>
              <div class="modal-body">
                <div class="row m-x-auto" id="containerDetalles">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade bd-example-modal-lg" id="modalDatosUsuario" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header border-primary">
                <span><%= image_tag('LogoCorona.png', class: 'rounded img-fluid', alt: 'Logo Corona') %></span>
                <h5 class="modal-title text-primary text-center" id="modalTitleUsuario">Datos Del Usuario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <br>
              <div class="modal-body">
                <div class="row" id="containerDatosUsuario">

                </div>
              </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="container" >
              <div class="row">
                <div class="col-md-4">
                  <div class="card border-primary mb-3" style="max-width: 20rem;">
                    <div class="card-header text-primary border-primary">Medidas para la construcci&oacute;n</div>
                    <div class="card-body text-primary">
                      <h4 class="card-title">Tu construcci&oacute;n</h4>
                      <p class="card-text">Visualiza aqu&iacute; tu proyecto</p>
                      <%= link_to image_tag('BañoIMGBASE.jpg', class: 'rounded img-fluid', alt: 'proyecto base') %>
                    </div>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="card border-primary mb-3" style="max-width: 20rem;">
                    <div class="card-header text-center text-primary border-primary">
                      <h2>Presupuesto Disponible</h2>
                    </div>
                    <div class="card-body text-primary">
                      <%= form_with model: @quotation, scope: :quotation, url: quotations_path, remote: true, id:"formCotizacion", class: "form-horizontal form-inline my-2 my-lg-0" do |form| %>
                      <div class="container">
                        <div class="row input-group">
                          <span class="input-group-addon text-primary">$</span>
                          <%= form.text_field :budget, class: "form-control", placeholder: "Ingrese su presupuesto", id:"budget"%>
                        </div>
                      </div>
                  </div>
                  <div class="card-footer bg-transparent border-primary">
                    <%= form.label :serviceInstall, '¿Desea incluir los servicios de instalación?', class: "form-check-label text-primary", id:"labelService" %>
                    <div class="container">
                      <br>
                      <div class="row">
                        <%= form.label :Si, class: "form-check-label col text-primary", id:"labelService" %>
                        <%= form.check_box :service, class: "form-check-input col", id:"service"%>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer bg-transparent border-primary"><%= form.label :projectState, 'Estado de la obra', class: "form-check-label text-primary", id:"labelEstadoObra" %>
                    <div class="container">
                      <br>
                      <div class="row">
                        <%= form.label :labelNegra, 'Obra Negra', class: "form-check-label col text-primary", id:"labelObraNegra" %>
                        <%= form.radio_button :project_status, "Obra Negra", class: "form-check-input col", id:"obraNegra"%></label>
                      </div>
                      <div class="row">
                        <%= form.label :labelBlanca, 'Obra Blanca', class: "form-check-label col text-primary", id:"labelObraBlanca" %>
                        <%= form.radio_button :project_status, "Obra Blanca", class: "form-check-input col", id:"obraBlanca"%>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer bg-transparent border-primary">
                    <%= form.submit "Generar Cotización", class: "btn btn-primary btn-lg btn-block container-fluid", 'data-toggle': "modal", 'data-target': ".bd-example-modal-lg" %>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="card border-primary mb-3" style="max-width: 20rem;">
                  <div class="card-header text-primary">
                    <%= form.label :labelTipoConstruccion, 'Tipo de construcción', id:"labelTipoConstruccion" %>
                    <%= form.select :name, options_for_select([['Baño', 'Baño'], ['Cocina','Cocina']]), {}, {:class => 'custom-select text-primary'} %>
                  </div>
                  <div class="card-footer bg-transparent border-primary">
                    <%= form.label :dimensionesPiso, 'Dimensiones Del Piso', class: "form-check-label col col text-primary", id:"labelDimPiso" %>
                    <div class="container">
                    <br>
                    <div class="row input-group">
                      <%= form.label :labelLength, 'Largo', class: "col-4 input-group-addon text-primary", id:"labelLength" %>
                      <%= form.text_field :floor_length, class: "col-8 form-control", placeholder: "Medida en metros", id:"length"%>
                    </div>
                    <div class="row input-group">
                      <%= form.label :labelWidth, 'Ancho', class: "col-4 input-group-addon text-primary", id:"labelWidth" %>
                      <%= form.text_field :floor_width, class: "form-control col-8 ", placeholder: "Medida en metros", id:"width"%>
                    </div>
                    </div>
                  </div>
                  <div class="card-footer bg-transparent border-primary">
                    <%= form.label :dimensionesPared, 'Dimensiones De la Pared', class: "form-check-label col col text-primary", id:"labelDimPared" %>
                    <div class="container">
                    <br>
                    <div class="row input-group">
                      <%= form.label :labelHeight, 'Alto', class: "col-4 input-group-addon text-primary", id:"labelWidth" %>
                      <%= form.text_field :wall_height, class: "col-8 form-control", placeholder: "Medida en metros", id:"widthPared"%>
                    </div>
                    <div class="row input-group">
                      <%= form.label :labelWidth, 'Ancho', class: "col-4 input-group-addon text-primary", id:"labelLength" %>
                      <%= form.text_field :wall_width, class: "col-8 form-control", placeholder: "Medida en metros", id:"lengthPared"%>
                    </div>
                    </div>
                  </div>
                  <div class="card-footer bg-transparent border-primary">
                    <%= form.label :dimensionesTecho, 'Dimensiones Del techo', class: "form-check-label col col text-primary", id:"labelDimTecho" %>
                    <div class="container">
                      <br>
                      <div class="row">
                        <%= form.label :lblIgualPiso, 'Igual al piso', class: "form-check-label col text-primary", id:"lblIgualPiso" %>
                        <%= form.check_box :igualPiso, class: "form-check-input col", id:"igualPiso"%>
                      </div>
                      <br>
                      <div class="row input-group" id="rowLengthTecho">
                        <%= form.label :labelLength, 'Largo', class: "col-4 input-group-addon text-primary", id:"labelLength" %>
                        <%= form.text_field :lengthTecho, class: "col-8 form-control", placeholder: "Medida en metros", id:"lengthTecho" %>
                      </div>
                      <div class="row input-group" id="rowWidthTecho">
                        <%= form.label :labelWidth, 'Ancho', class: "col-4 input-group-addon text-primary", id:"labelWidth" %>
                        <%= form.text_field :widthTecho, class: "col-8 form-control", placeholder: "Medida en metros", id:"widthTecho"%>
                      </div>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
            </div>

<!-- $$$$$$$$$$$$$$$$$$$$$   hasta aca container formulario   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<br>
  <!-- $$$$$$$$$$$$$$$$$$$$$   Container de la imagen y desgloce cotizacion   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
    <div class="row" >
      <div class="container">
        <div class="row">
        <div class="col-md-12" align="center" id="contenidoCotizacion">

        </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <br>
            <br>
          </div>
        </div>
      </div>
    </div>
</div>